# Generated by Django 5.2.4 on 2025-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('specs', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new-request', 'New Request'), ('agent-working', 'Agent Working'), ('awaiting-approval', 'Awaiting Approval'), ('rfqs-sent', 'RFQs Sent'), ('quotes-received', 'Quotes Received'), ('finalized', 'Finalized')], default='new-request', max_length=50)),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('Bulk Upload', 'Bulk Upload')], default='Manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotes_in', models.IntegerField(default=0)),
                ('total_quotes_sent', models.IntegerField(default=0)),
            ],
        ),
    ]
