# Generated by Django 5.2.4 on 2025-08-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('specs', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new-request', 'New Request'), ('agent-working', 'Agent Working'), ('awaiting-approval', 'Awaiting Approval'), ('rfqs-sent', 'RFQs Sent'), ('quotes-received', 'Quotes Received'), ('finalized', 'Finalized')], default='new-request', max_length=50)),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('Bulk Upload', 'Bulk Upload')], default='Manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotes_in', models.IntegerField(default=0)),
                ('total_quotes_sent', models.IntegerField(default=0)),
                ('estimated_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed_from_email_uid', models.CharField(max_length=100, unique=True)),
                ('full_email_body', models.TextField(blank=True, null=True)),
                ('procurement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='procurement.procurementrequest')),
            ],
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for_request', to='procurement.quote'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source_link', models.URLField(blank=True, max_length=500, null=True)),
                ('indiamart_rfq_sent', models.BooleanField(default=False)),
                ('procurement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='procurement.procurementrequest')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier'),
        ),
    ]
