# Generated by Django 5.2.4 on 2025-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_supplier_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='full_email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
