# Generated by Django 5.2.1 on 2025-07-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_quote_full_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='estimated_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for_request', to='procurement.quote'),
        ),
    ]
