# Generated by Django 6.0.1 on 2026-01-17 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_thumbnail', models.URLField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('subreddit', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField(blank=True, help_text='Original Reddit content')),
                ('rewritten_content', models.TextField(help_text='AI-rewritten content')),
                ('custom_instruction', models.TextField(blank=True, help_text='Custom style/tone instructions for Gemini')),
                ('image_source', models.CharField(choices=[('pexels', 'Pexels'), ('giphy', 'Giphy'), ('serpapi', 'SerpApi'), ('upload', 'Local Upload'), ('ai_generated', 'AI Generated')], max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_query', models.CharField(blank=True, help_text='Search query for image APIs', max_length=200)),
                ('linkedin_urn', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reddit_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkedin_posts', to='linkedin_automation.redditpost')),
            ],
            options={
                'verbose_name_plural': 'Post Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('headline', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('profile_picture', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('follower_count', models.CharField(blank=True, max_length=50)),
                ('employee_count', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('ai_outreach_message', models.TextField(blank=True, help_text='AI-generated outreach message')),
                ('contacted', models.BooleanField(default=False)),
                ('contacted_date', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('profile_type', 'name', 'linkedin_url')},
            },
        ),
    ]
