# Generated by Django 5.2.4 on 2025-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the template.', max_length=100, unique=True)),
                ('html_content', models.TextField(help_text='The full HTML content of the email template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
