# Generated by Django 5.2.4 on 2025-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent_pitch', '0002_campaign_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, help_text="The recipient's name.", max_length=255),
        ),
    ]
