# Generated by Django 6.0 on 2025-12-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='rfq_sent_time',
            field=models.DateTimeField(blank=True, help_text='Time when RFQ was sent', null=True),
        ),
    ]
