# Generated by Django 6.0 on 2026-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_procurementrequest_rfq_sent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='quotes/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='source_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
